=== minuk926/xit-adds-parent/adds-api/src/test/resources/exchange_mis.dtd
<?xml version="1.0" encoding="EUC-KR"?>
    <!ELEMENT EXCHANGE (HEADER, BODY?, ATTACHMENTS?, ADMINISTRATIVE_INFO?)>
    <!ELEMENT HEADER (COMMON, DIRECTION, ADDENDA?)>
    <!ELEMENT COMMON (SENDER, RECEIVER, TITLE, CREATED_DATE, ATTACHNUM, ADMINISTRATIVE_NUM)>
    <!ELEMENT SENDER (SERVERID, USERID, EMAIL?)>
    <!ELEMENT RECEIVER (SERVERID, USERID, EMAIL?)>
    <!ELEMENT SERVERID (#PCDATA)>
    <!ELEMENT USERID (#PCDATA)>
    <!ELEMENT EMAIL (#PCDATA)>
    <!ELEMENT TITLE (#PCDATA)>
    <!ELEMENT CREATED_DATE (#PCDATA)>
    <!ELEMENT ATTACHNUM (#PCDATA)>
    <!ELEMENT ADMINISTRATIVE_NUM (#PCDATA)>
    <!ELEMENT DIRECTION (TO_ADMINISTRATIVE_SYSTEM | TO_DOCUMENT_SYSTEM)>
    <!ELEMENT TO_ADMINISTRATIVE_SYSTEM (DOCNUM, SANCTION_INFO, MODIFICATION_FLAG, BODY_MODIFICATIONFLAG?, BODY_TEXT?)>
    <!ELEMENT DOCNUM (#PCDATA)>
    <!ATTLIST DOCNUM docnumcode CDATA #REQUIRED >
    <!ELEMENT SANCTION_INFO (LINES)>
    <!ATTLIST SANCTION_INFO
        status (진행| 완료) #REQUIRED>
    <!ELEMENT LINES (LINE+)>
    <!ELEMENT LINE (LEVEL, SANCTION)>
    <!ELEMENT LEVEL (#PCDATA)>
    <!ELEMENT SANCTION (PERSON, COMMENT?, DATE)>
    <!ATTLIST SANCTION
        type (기안 | 검토 | 협조 | 병렬협조 | 결재 | 전결 | 대결 | 전대결) #REQUIRED
        result (상신 | 결재 | 1인결재 | 중단 | 재검토 | 협조 | 공석 | 미처리) "미처리">
    <!ELEMENT PERSON (USERID, NAME, POSITION, DEPT, ORG)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT POSITION (#PCDATA)>
    <!ELEMENT DEPT (#PCDATA)>
    <!ELEMENT ORG (#PCDATA)>
    <!ELEMENT COMMENT (#PCDATA)>
    <!ELEMENT DATE (#PCDATA)>
    <!ELEMENT MODIFICATION_FLAG (MODIFIABLE, MODIFIED?)>
    <!ELEMENT MODIFIABLE EMPTY>
    <!ATTLIST MODIFIABLE
        modifyflag (yes | no) "no" >
    <!ELEMENT MODIFIED (#PCDATA)>
    <!ELEMENT BODY_MODIFICATIONFLAG (BODY_MODIFIABLE, BODY_MODIFIED?)>
    <!ELEMENT BODY_MODIFIABLE EMPTY>
    <!ATTLIST BODY_MODIFIABLE
        modifyflag (yes | no) "yes" >
    <!ELEMENT BODY_MODIFIED (#PCDATA)>
    <!ELEMENT BODY_TEXT (#PCDATA)>
    <!ELEMENT TO_DOCUMENT_SYSTEM (LINES?, MODIFICATION_FLAG, BODY_MODIFICATIONFLAG?, DOC_INFO?)>
    <!ATTLIST TO_DOCUMENT_SYSTEM
        notification (all | final | none) "all" >
    <!ELEMENT DOC_INFO (SUMMARY?, DOCGUBUN?, READINGBOUND?, READINGLIMIT?,    PUBLICATION?, TASKCARDS?, SOURCES?, TO_KMS?, TO_UNIKMS?, SENDORGNAME?, ENFORCEMENT?)>
    <!ELEMENT SUMMARY (#PCDATA)>
    <!ELEMENT DOCGUBUN (#PCDATA)>
    <!ATTLIST DOCGUBUN
        type (dopt1 | dopt2) "dopt1" >
    <!ELEMENT READINGBOUND (#PCDATA)>
    <!ATTLIST READINGBOUND
        type (all | organ | div | dept | line) #REQUIRED >
    <!ELEMENT READINGLIMIT (#PCDATA)>
    <!ATTLIST READINGLIMIT
        type (none | progress | setdate) "none">
    <!ATTLIST READINGLIMIT
        date CDATA #IMPLIED>
    <!ELEMENT PUBLICATION (#PCDATA)>
    <!ATTLIST PUBLICATION
        code CDATA #REQUIRED
        reason CDATA #IMPLIED >
    <!ELEMENT TASKCARDS (TASKCARD+)>
    <!ELEMENT TASKCARD (CARDNAME, CARDID)>
    <!ATTLIST TASKCARD
        type (bis | pjt | org) #REQUIRED >
    <!ELEMENT CARDNAME (#PCDATA)>
    <!ELEMENT CARDID (#PCDATA)>
    <!ELEMENT SOURCES (DIRECT?, INSTRUCTION*, DOCUMENT*, MEMO*)>
    <!ELEMENT DIRECT (TITLE, INSTRUCTED?)>
    <!ELEMENT INSTRUCTED (FILE+)>
    <!ELEMENT FILE (ORDER, FILENAME, DISPLAYNAME)>
    <!ELEMENT ORDER (#PCDATA)>
    <!ELEMENT FILENAME (#PCDATA)>
    <!ELEMENT DISPLAYNAME (#PCDATA)>
    <!ELEMENT INSTRUCTION (TITLE, INSTRUCTIONID)>
    <!ELEMENT INSTRUCTIONID (#PCDATA)>
    <!ELEMENT DOCUMENT (TITLE, DOCID)>
    <!ATTLIST DOCUMENT
        type (doc | enf) #REQUIRED >
    <!ELEMENT DOCID (#PCDATA)>
    <!ELEMENT MEMO (TITLE, MEMOID)>
    <!ELEMENT MEMOID (#PCDATA)>
    <!ELEMENT TO_KMS (MAPCODE,MAPNAME)>
    <!ATTLIST TO_KMS
        sendflag (yes | no) "no" >
    <!ELEMENT MAPCODE (#PCDATA)>
    <!ELEMENT MAPNAME (#PCDATA)>
    <!ELEMENT TO_UNIKMS EMPTY>
    <!ATTLIST TO_UNIKMS
        sendflag (yes | no) "no" >
    <!ELEMENT SENDORGNAME (#PCDATA)>
    <!ELEMENT ENFORCEMENT (SENDNAME, RECEIPT*, EXRECEIPT?)>
    <!ELEMENT SENDNAME (#PCDATA)>
    <!ELEMENT RECEIPT (ORG, ORGCODE, DEPT?, DEPTCODE?)>
    <!ATTLIST RECEIPT
        refer  (yes | no) "no" >
    <!ELEMENT ORGCODE (#PCDATA)>
    <!ELEMENT DEPTCODE (#PCDATA)>
    <!ELEMENT EXRECEIPT ((EXTERNAL | PUBLICORG | PRIVATEORG | CIVILIAN)+)>
    <!ELEMENT EXTERNAL (ORG, ORGCODE, DEPT?, DEPTCODE?, ORGTYPE, SYSTEMTYPE, FLOWTYPE)>
    <!ATTLIST EXTERNAL
        refer  (yes | no) "no" >
    <!ELEMENT ORGTYPE (#PCDATA)>
    <!ATTLIST ORGTYPE
        typecode  (GOV | PUB | CIVIL) "GOV" >
    <!ELEMENT SYSTEMTYPE (#PCDATA)>
    <!ATTLIST SYSTEMTYPE
        typecode  (A | O) "A" >
    <!ELEMENT FLOWTYPE (#PCDATA)>
    <!ATTLIST FLOWTYPE
        typecode  (DRT01 | DRT02 | DRT03) "DRT01" >
    <!ELEMENT PUBLICORG (ORG, DEPT?, SYMBOL?)>
    <!ELEMENT SYMBOL (#PCDATA)>
    <!ELEMENT PRIVATEORG (ORG, DEPT?, FAX?)>
    <!ELEMENT FAX (#PCDATA)>
    <!ELEMENT CIVILIAN (NAME, TEL?, FAX?, POST?, ADDRESS?)>
    <!ELEMENT TEL (#PCDATA)>
    <!ELEMENT POST (#PCDATA)>
    <!ELEMENT ADDRESS (#PCDATA)>
    <!ELEMENT ADDENDA (ADDENDUM+)>
    <!ELEMENT ADDENDUM (#PCDATA)>
    <!ATTLIST ADDENDUM
        name CDATA #REQUIRED
        comment CDATA #REQUIRED >
    <!ELEMENT BODY (#PCDATA)>
    <!ATTLIST BODY
        filename CDATA #IMPLIED
        desc CDATA #IMPLIED >
    <!ELEMENT ATTACHMENTS (ADMINISTRATIVE_DB?, (ATTACHMENT*))>
    <!ELEMENT ADMINISTRATIVE_DB (XMLFILE?, XSLFILE?)>
    <!ELEMENT XMLFILE (#PCDATA)>
    <!ATTLIST XMLFILE
        filename CDATA #REQUIRED
        desc CDATA #IMPLIED >
    <!ELEMENT XSLFILE (#PCDATA)>
    <!ATTLIST XSLFILE
        filename CDATA #REQUIRED
        desc CDATA #IMPLIED >
    <!ELEMENT ATTACHMENT (#PCDATA)>
    <!ATTLIST ATTACHMENT
        filename CDATA #REQUIRED
        desc CDATA #IMPLIED >
    <!ELEMENT ADMINISTRATIVE_INFO (FORM_FILE?, FORM_INFO?, FORM_DATA?)>
    <!ELEMENT FORM_FILE (#PCDATA)>
    <!ATTLIST FORM_FILE
        filename CDATA #REQUIRED
        desc CDATA #IMPLIED >
    <!ELEMENT FORM_INFO (#PCDATA)>
    <!ATTLIST FORM_INFO
        sys_id CDATA #REQUIRED
        biz_id CDATA #REQUIRED
        seq CDATA #IMPLIED >
    <!ELEMENT FORM_DATA ((DATA_FIELD | REPETITION_DATA_FIELD)+)>
    <!ELEMENT DATA_FIELD (FIELD_NAME, FIELD_VALUE)>
    <!ATTLIST DATA_FIELD
        modifyflag (yes | no) "no" >
    <!ELEMENT FIELD_NAME (#PCDATA)>
    <!ELEMENT FIELD_VALUE (#PCDATA)>
    <!ELEMENT REPETITION_DATA_FIELD (FIELD_NAME, FIELD_VALUE, ROW, COLUMN)>
    <!ATTLIST REPETITION_DATA_FIELD
        modifyflag (yes | no) "no" >
    <!ELEMENT ROW (#PCDATA)>
    <!ELEMENT COLUMN (#PCDATA)>

=== minuk926/xit-adds-parent/adds-api/src/test/resources/open_exchange_exchange.xml
<?xml version="1.0" encoding="EUC-KR"?>
<!DOCTYPE EXCHANGE SYSTEM "exchange_mis.dtd">
<EXCHANGE>
	<HEADER>
		<COMMON>
			<SENDER>
				<SERVERID>DOC999999901</SERVERID>
				<USERID>admin</USERID>
				<EMAIL/>
			</SENDER>
			<RECEIVER>
				<SERVERID>DOC123456701</SERVERID>
				<USERID>admin</USERID>
			</RECEIVER>
			<TITLE>TEST TITLE_DOC</TITLE>
			<CREATED_DATE>2020-12-08 14:00:00</CREATED_DATE>
			<ATTACHNUM>1</ATTACHNUM>
			<ADMINISTRATIVE_NUM>TEST1234567890</ADMINISTRATIVE_NUM>
		</COMMON>
		<DIRECTION>
			<TO_DOCUMENT_SYSTEM notification="all">
				<MODIFICATION_FLAG>
					<MODIFIABLE modifyflag="yes"/>
				</MODIFICATION_FLAG>
			</TO_DOCUMENT_SYSTEM>
		</DIRECTION>
	</HEADER>
	<BODY><![CDATA[연계테스트 문서입니다.]]></BODY>
	<ATTACHMENTS>
		<ATTACHMENT filename="attach_attach_title.txt">TEST_ATTACH.txt</ATTACHMENT>
	</ATTACHMENTS>
</EXCHANGE>
